# Generated by Django 4.0.5 on 2022-07-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
