# Generated by Django 4.0.5 on 2022-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('MOD', 'На модерацию'), ('PUB', 'Опубликовано'), ('REJ', 'Отклонено'), ('DEL', 'На удаление')], default='на модерацию', max_length=30, verbose_name='Статус'),
        ),
    ]
