# Generated by Django 4.0.5 on 2022-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('MOD', 'На модерацию'), ('PUB', 'Опубликовано'), ('REJ', 'Отклонено'), ('DEL', 'На удаление')], default='MOD', max_length=30, verbose_name='Статус'),
        ),
    ]
