# Generated by Django 4.0.5 on 2022-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фотография'),
        ),
    ]
